[nodejs]
disabled = true

[lua]
# disabled = true

[python]
symbol = "îœ¼ "
disabled = true

[rlang]
disabled = true

[scala]
symbol = "îœ· "
disabled = true

[java]
symbol = "ó°¬· "
# disabled = true
# detect_files = 'pom.xml'

[character] # The name of the module we are configuring is 'character'
# success_symbol = '[âžœ](bold green)'
# disabled = true

[line_break]
# disabled = true

[shell]
disabled = false
nu_indicator =  "ðŸ‡³ ðŸ‡º"
fish_indicator = ""
